version: '3.8'

services:
  # Base de Datos Transaccional (OLTP)
  postgres_oltp:
    image: postgres:15
    container_name: postgres_oltp
    restart: always
    environment:
      POSTGRES_USER: Portafolio2026@
      POSTGRES_PASSWORD: Portafolio2026@ 
      POSTGRES_DB: Source
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
      - ./init_db:/docker-entrypoint-initdb.d # Para cargar datos automáticamente al iniciar

  # (Opcional) Interfaz visual para la BD
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_container
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8080:80"
    depends_on:
      - postgres_oltp

      # Orquestación con Airflow
  airflow-webserver:
    image: apache/airflow:2.7.1-python3.10
    container_name: airflow_webserver
    command: webserver
    entrypoint: [/bin/bash, -c, "airflow db init && airflow users create --username admin --firstname Albert --lastname DataMaster --role Admin --email admin@example.com --password admin && airflow webserver"]
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql+psycopg2://Portafolio2026%40:Portafolio2026%40@postgres_oltp:5432/Source
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
      - _PIP_ADDITIONAL_REQUIREMENTS=apache-airflow-providers-google
    ports:
      - "8081:8080"
    volumes:
      - ./dags:/opt/airflow/dags
      - .:/opt/airflow/
      - ./data:/opt/airflow/data
    depends_on:
      - postgres_oltp

  airflow-scheduler:
    image: apache/airflow:2.7.1-python3.10
    container_name: airflow_scheduler
    command: scheduler
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql+psycopg2://Portafolio2026%40:Portafolio2026%40@postgres_oltp:5432/Source
      - AIRFLOW__CORE__TEST_CONNECTION=Enabled
      - _PIP_ADDITIONAL_REQUIREMENTS=apache-airflow-providers-google
    volumes:
      - ./dags:/opt/airflow/dags
      - .:/opt/airflow/
      - ./credentials:/opt/airflow/credentials
    depends_on:
      - postgres_oltp